function t = term3(rrobx,rroby,vobs,vrob,w0,theta0,dt,vr,w,R)
  t=2.*dt.*(vr+vrob).*w.*(dt.*(rroby.*cos(theta0+dt.*(w+w0))+(-1).* ...
  rrobx.*sin(theta0+dt.*(w+w0))).*(2.*vobs.^2+(vr+vrob).^2+(-2).* ...
  vobs.*(vr+vrob).*(cos(theta0+dt.*(w+w0))+sin(theta0+dt.*(w+w0))))+ ...
  ((rroby+dt.*vobs).*cos(theta0+dt.*(w+w0))+(-1).*(rrobx+dt.*vobs).* ...
  sin(theta0+dt.*(w+w0))).*((-1).*(rrobx+rroby).*vobs+(-1).*dt.*(vr+ ...
  vrob).^2+(vr+vrob).*((rrobx+dt.*vobs).*cos(theta0+dt.*(w+w0))+( ...
  rroby+dt.*vobs).*sin(theta0+dt.*(w+w0))))+(-1).*vobs.*(cos(theta0+ ...
  dt.*(w+w0))+(-1).*sin(theta0+dt.*(w+w0))).*(R.^2+(-1).*(rrobx+(-1) ...
  .*dt.*(vr+vrob).*cos(theta0+dt.*(w+w0))).^2+(-1).*(rroby+(-1).* ...
  dt.*(vr+vrob).*sin(theta0+dt.*(w+w0))).^2));
 
end