function t = term1(rrobx,rroby,vrob,vobs,R,w0,theta0,dt)
 t=((vobs+(-1).*vrob.*cos(theta0+dt.*w0)).*(rrobx+(-1).*dt.*vrob.* ...
  cos(theta0+dt.*w0))+(vobs+(-1).*vrob.*sin(theta0+dt.*w0)).*(rroby+ ...
  (-1).*dt.*vrob.*sin(theta0+dt.*w0))).^2+((vobs+(-1).*vrob.*cos( ...
  theta0+dt.*w0)).^2+(vobs+(-1).*vrob.*sin(theta0+dt.*w0)).^2).*( ...
  R.^2+(-1).*(rrobx+(-1).*dt.*vrob.*cos(theta0+dt.*w0)).^2+(-1).*( ...
  rroby+(-1).*dt.*vrob.*sin(theta0+dt.*w0)).^2);
 
end